spring.application.name=mi-proyecto

spring.datasource.url=jdbc:postgresql://localhost:5432/facturacion
spring.datasource.username=facturacion
spring.datasource.password=facturacion

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# API Laravel (otro microservicio / servicio externo)
laravel.api.base-url=http://localhost:8000
laravel.api.token=2|xslqCf1KgAO08AVF7PIdiajVi5JRnNr4ndYoTGVk83ff6d67
